backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/site.yml"
        label: "Configurações gerais"
        name: "site"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
